#ifndef ICONS_H
#define ICONS_H

// Glyph indices for u8g2_font_open_iconic_all_2x_t.
// 223 icons from Open Iconic, mapped sequentially starting at decimal 64.
// Reference: https://github.com/iconic/open-iconic
//            https://github.com/olikraus/u8g2/wiki/fntgrpiconic

#define ICON_ACCOUNT_LOGIN              64
#define ICON_ACCOUNT_LOGOUT             65
#define ICON_ACTION_REDO                66
#define ICON_ACTION_UNDO                67
#define ICON_ALIGN_CENTER               68
#define ICON_ALIGN_LEFT                 69
#define ICON_ALIGN_RIGHT                70
#define ICON_APERTURE                   71
#define ICON_ARROW_BOTTOM               72
#define ICON_ARROW_CIRCLE_BOTTOM        73
#define ICON_ARROW_CIRCLE_LEFT          74
#define ICON_ARROW_CIRCLE_RIGHT         75
#define ICON_ARROW_CIRCLE_TOP           76
#define ICON_ARROW_LEFT                 77
#define ICON_ARROW_RIGHT                78
#define ICON_ARROW_THICK_BOTTOM         79
#define ICON_ARROW_THICK_LEFT           80
#define ICON_ARROW_THICK_RIGHT          81
#define ICON_ARROW_THICK_TOP            82
#define ICON_ARROW_TOP                  83
#define ICON_AUDIO_SPECTRUM             84
#define ICON_AUDIO                      85
#define ICON_BADGE                      86
#define ICON_BAN                        87
#define ICON_BAR_CHART                  88
#define ICON_BASKET                     89
#define ICON_BATTERY_EMPTY              90
#define ICON_BATTERY_FULL               91
#define ICON_BEAKER                     92
#define ICON_BELL                       93
#define ICON_BLUETOOTH                  94
#define ICON_BOLD                       95
#define ICON_BOLT                       96
#define ICON_BOOK                       97
#define ICON_BOOKMARK                   98
#define ICON_BOX                        99
#define ICON_BRIEFCASE                  100
#define ICON_BRITISH_POUND              101
#define ICON_BROWSER                    102
#define ICON_BRUSH                      103
#define ICON_BUG                        104
#define ICON_BULLHORN                   105
#define ICON_CALCULATOR                 106
#define ICON_CALENDAR                   107
#define ICON_CAMERA_SLR                 108
#define ICON_CARET_BOTTOM               109
#define ICON_CARET_LEFT                 110
#define ICON_CARET_RIGHT                111
#define ICON_CARET_TOP                  112
#define ICON_CART                       113
#define ICON_CHAT                       114
#define ICON_CHECK                      115
#define ICON_CHEVRON_BOTTOM             116
#define ICON_CHEVRON_LEFT               117
#define ICON_CHEVRON_RIGHT              118
#define ICON_CHEVRON_TOP                119
#define ICON_CIRCLE_CHECK               120
#define ICON_CIRCLE_X                   121
#define ICON_CLIPBOARD                  122
#define ICON_CLOCK                      123
#define ICON_CLOUD_DOWNLOAD             124
#define ICON_CLOUD_UPLOAD               125
#define ICON_CLOUD                      126
#define ICON_CLOUDY                     127
#define ICON_CODE                       128
#define ICON_COG                        129
#define ICON_COLLAPSE_DOWN              130
#define ICON_COLLAPSE_LEFT              131
#define ICON_COLLAPSE_RIGHT             132
#define ICON_COLLAPSE_UP                133
#define ICON_COMMAND                    134
#define ICON_COMMENT_SQUARE             135
#define ICON_COMPASS                    136
#define ICON_CONTRAST                   137
#define ICON_COPYWRITING                138
#define ICON_CREDIT_CARD                139
#define ICON_CROP                       140
#define ICON_DASHBOARD                  141
#define ICON_DATA_TRANSFER_DOWNLOAD     142
#define ICON_DATA_TRANSFER_UPLOAD       143
#define ICON_DELETE                     144
#define ICON_DIAL                       145
#define ICON_DOCUMENT                   146
#define ICON_DOLLAR                     147
#define ICON_DOUBLE_QUOTE_SANS_LEFT     148
#define ICON_DOUBLE_QUOTE_SANS_RIGHT    149
#define ICON_DOUBLE_QUOTE_SERIF_LEFT    150
#define ICON_DOUBLE_QUOTE_SERIF_RIGHT   151
#define ICON_DROPLET                    152
#define ICON_EJECT                      153
#define ICON_ELEVATOR                   154
#define ICON_ELLIPSES                   155
#define ICON_ENVELOPE_CLOSED            156
#define ICON_ENVELOPE_OPEN              157
#define ICON_EURO                       158
#define ICON_EXCERPT                    159
#define ICON_EXPAND_DOWN                160
#define ICON_EXPAND_LEFT                161
#define ICON_EXPAND_RIGHT               162
#define ICON_EXPAND_UP                  163
#define ICON_EXTERNAL_LINK              164
#define ICON_EYE                        165
#define ICON_EYEDROPPER                 166
#define ICON_FILE                       167
#define ICON_FIRE                       168
#define ICON_FLAG                       169
#define ICON_FLASH                      170
#define ICON_FOLDER                     171
#define ICON_FORK                       172
#define ICON_FULLSCREEN_ENTER           173
#define ICON_FULLSCREEN_EXIT            174
#define ICON_GLOBE                      175
#define ICON_GRAPH                      176
#define ICON_GRID_FOUR_UP               177
#define ICON_GRID_THREE_UP              178
#define ICON_GRID_TWO_UP                179
#define ICON_HARD_DRIVE                 180
#define ICON_HEADER                     181
#define ICON_HEADPHONES                 182
#define ICON_HEART                      183
#define ICON_HOME                       184
#define ICON_IMAGE                      185
#define ICON_INBOX                      186
#define ICON_INFINITY                   187
#define ICON_INFO                       188
#define ICON_ITALIC                     189
#define ICON_JUSTIFY_CENTER             190
#define ICON_JUSTIFY_LEFT               191
#define ICON_JUSTIFY_RIGHT              192
#define ICON_KEY                        193
#define ICON_LAPTOP                     194
#define ICON_LAYERS                     195
#define ICON_LIGHTBULB                  196
#define ICON_LINK_BROKEN                197
#define ICON_LINK_INTACT                198
#define ICON_LIST_RICH                  199
#define ICON_LIST                       200
#define ICON_LOCATION                   201
#define ICON_LOCK_LOCKED                202
#define ICON_LOCK_UNLOCKED              203
#define ICON_LOOP_CIRCULAR              204
#define ICON_LOOP_SQUARE                205
#define ICON_LOOP                       206
#define ICON_MAGNIFYING_GLASS           207
#define ICON_MAP_MARKER                 208
#define ICON_MAP                        209
#define ICON_MEDIA_PAUSE                210
#define ICON_MEDIA_PLAY                 211
#define ICON_MEDIA_RECORD               212
#define ICON_MEDIA_SKIP_BACKWARD        213
#define ICON_MEDIA_SKIP_FORWARD         214
#define ICON_MEDIA_STEP_BACKWARD        215
#define ICON_MEDIA_STEP_FORWARD         216
#define ICON_MEDIA_STOP                 217
#define ICON_MEDICAL_CROSS              218
#define ICON_MENU                       219
#define ICON_MICROPHONE                 220
#define ICON_MINUS                      221
#define ICON_MONITOR                    222
#define ICON_MOON                       223
#define ICON_MOVE                       224
#define ICON_MUSICAL_NOTE               225
#define ICON_PAPERCLIP                  226
#define ICON_PENCIL                     227
#define ICON_PEOPLE                     228
#define ICON_PERSON                     229
#define ICON_PHONE                      230
#define ICON_PIE_CHART                  231
#define ICON_PIN                        232
#define ICON_PLAY_CIRCLE                233
#define ICON_PLUS                       234
#define ICON_POWER_STANDBY              235
#define ICON_PRINT                      236
#define ICON_PROJECT                    237
#define ICON_PULSE                      238
#define ICON_PUZZLE_PIECE               239
#define ICON_QUESTION_MARK              240
#define ICON_RAIN                       241
#define ICON_RANDOM                     242
#define ICON_RELOAD                     243
#define ICON_RESIZE_BOTH                244
#define ICON_RESIZE_HEIGHT              245
#define ICON_RESIZE_WIDTH               246
#define ICON_RSS_ALT                    247
#define ICON_RSS                        248
#define ICON_SCRIPT                     249
#define ICON_SHARE_BOXED                250
#define ICON_SHARE                      251
#define ICON_SHIELD                     252
#define ICON_SIGNAL                     253
#define ICON_SIGNPOST                   254
#define ICON_SORT_ASCENDING             255
#define ICON_SORT_DESCENDING            256
#define ICON_SPREADSHEET                257
#define ICON_STAR                       258
#define ICON_SUN                        259
#define ICON_TABLET                     260
#define ICON_TAG                        261
#define ICON_TAGS                       262
#define ICON_TARGET                     263
#define ICON_TASK                       264
#define ICON_TERMINAL                   265
#define ICON_TEXT                       266
#define ICON_THUMB_DOWN                 267
#define ICON_THUMB_UP                   268
#define ICON_TIMER                      269
#define ICON_TRANSFER                   270
#define ICON_TRASH                      271
#define ICON_UNDERLINE                  272
#define ICON_VERTICAL_ALIGN_BOTTOM      273
#define ICON_VERTICAL_ALIGN_CENTER      274
#define ICON_VERTICAL_ALIGN_TOP         275
#define ICON_VIDEO                      276
#define ICON_VOLUME_HIGH                277
#define ICON_VOLUME_LOW                 278
#define ICON_VOLUME_OFF                 279
#define ICON_WARNING                    280
#define ICON_WIFI                       281
#define ICON_WRENCH                     282
#define ICON_X                          283
#define ICON_YEN                        284
#define ICON_ZOOM_IN                    285
#define ICON_ZOOM_OUT                   286

#endif // ICONS_H
